spring:
  application:
    name: batch

  datasource:
    hikari:
      maximum-pool-size: 10
      username: root
      password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/batch"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    #    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      name: MEMBER_DELETE_JOB


  # H2
  #  datasource:
  #    url: "jdbc:h2:tcp://localhost/./batch"
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password: 1234

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
