spring:
  application:
    name: batch

  datasource:
    url: "jdbc:h2:tcp://localhost/./batch"
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  batch:
    jdbc:
      initialize-schema: always
    job:
      name: JDBC_PAGING_CHUNK_JOB
